### ISSUE TITLE
Incompatibility with Towny Advanced

### ISSUE THREAD

**Issue by paulhlschr** [lokka30/PhantomEconomy#25]
When trying to create a Towny town, the following error occurs.
I am not sure, from which site this plugin is being caused. Therefor I will report this error here and on Towny's site. I hope, that's okay :x 

> [19:54:55 WARN]: java.lang.NumberFormatException: For input string: "{enabled=true, amount=50.00}"
> [19:54:55 WARN]:        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
> [19:54:55 WARN]:        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> [19:54:55 WARN]:        at java.lang.Double.parseDouble(Double.java:538)
> [19:54:55 WARN]:        at io.github.lokka30.phantomeconomy.lightningstorage.util.ClassWrapper$DOUBLE.getDouble(ClassWrapper.java:124)
> [19:54:55 WARN]:        at io.github.lokka30.phantomeconomy.lightningstorage.util.ClassWrapper.getFromDef(ClassWrapper.java:27)
> [19:54:55 WARN]:        at io.github.lokka30.phantomeconomy.lightningstorage.internal.DataStorage.get(DataStorage.java:65)
> [19:54:55 WARN]:        at io.github.lokka30.phantomeconomy.VaultImplementer.createPlayerAccount(VaultImplementer.java:312)
> [19:54:55 WARN]:        at io.github.lokka30.phantomeconomy.VaultImplementer.createPlayerAccount(VaultImplementer.java:304)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:258)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingBalance(EconomyAccount.java:174)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.object.EconomyAccount.setBalance(EconomyAccount.java:151)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.command.TownCommand.newTown(TownCommand.java:2440)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.command.TownCommand.newTown(TownCommand.java:2394)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.command.TownyAdminCommand.parseAdminTownCommand(TownyAdminCommand.java:874)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.command.TownyAdminCommand.parseTownyAdminCommand(TownyAdminCommand.java:434)
> [19:54:55 WARN]:        at com.palmergames.bukkit.towny.command.TownyAdminCommand.onCommand(TownyAdminCommand.java:229)
> [19:54:55 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [19:54:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
> [19:54:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
> [19:54:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
> [19:54:55 WARN]:        at java.lang.Thread.run(Thread.java:748)

Running on Paper 1.15.2 with PhantomEconomy 1.7 and Towny 0.96.1.2

**Comment by lokka30** [comment]
Hi, i need more information, but from what i can assume it's Towny not using a Vault method correctly? I have no idea. as i said more information please

**Comment by paulhlschr** [comment]
Hey! I should have written more about the issue right away.
The given stacktrace occurs, when trying to execute the Towny command `/townyadmin town new`.
As I am not really into Minecraft plugin development I am not sure, which plugin is causing this error. I assume the error occurs, because Towny is trying to get the balance of the player, as creating a new town costs 250 (My balance is 50). Despite the error, the city is created at the end, so it doesn't seem to block Towny any further, so I think it's more of a Phantomeconomy error. But feel free to prove me wrong :D

**Edit:**
Running any town-related commands throw the given exception. Towny tries to read the player's balance, but is not able to.

[latest.log](https://pastebin.com/VSqzJsHP)

### Server Software
Paper 1.15.2 #149
### Plugin Versions
- PhantomEconomy 1.7 RELEASE
- Towny Advanced 0.96.1.2

**Comment by paulhlschr** [comment]
Seems like, the error is on your end:
https://github.com/TownyAdvanced/Towny/issues/3891#issuecomment-610587849

**Comment by lokka30** [comment]
Hi paul, please could you send me your settings.yml file?
I believe that you have put an invalid number in 'default-balance'.

But this is something interesting:
`java.lang.NumberFormatException: For input string: "{enabled=true, amount=50.00}"`
Something is trying to put in 'enabled=true, amount=50.00' as a number?

**Comment by paulhlschr** [comment]
Hey again!
Here is the [settings.yml](https://pastebin.com/ZmgFKE9c) you asked for. (I got it via my phone, I hope it worked properly.)

Indeed, the input string is interesting. But in my setup there shouldn't be anything, that manipulates the way Towny and PE interact through Vault with each other. I would check it right now, but it's 02:24 here in Germany already, so please excuse the delays :D

**Comment by lokka30** [comment]
Thanks!

**Comment by lokka30** [comment]
Found an issue, not sure if it is related, but it was using the wrong path to get the default balance. Fixed in an upcoming release.

**Comment by lokka30** [comment]
Just posted an update, did it fix the issue? https://www.spigotmc.org/resources/phantomeconomy-your-simple-open-source-economy.75053/

**Comment by paulhlschr** [comment]
It **did** fix the issue. Thank you very much for the quick response and fix! :)

**Comment by paulhlschr** [comment]
Sadly I need to reopen the issue, as it seems to be just fixed partly. I talked with the Towny dev on their Discord server regarding additional errors, that occur (e.g. depositing money into a town's bank account  etc.).

Towny's lead developer suspects that PE has not implemented all of the required Vault methods, so Towny cannot access them. This is probably what causes the incompatibility. He kindly sent me the section in his code where you are supposed to find all the Vault methods that Towny uses.
You should find them from line 157 onwards here: https://github.com/TownyAdvanced/Towny/blob/480fa6efa07647ea373e99bb995616af94a54c29/src/com/palmergames/bukkit/towny/TownyEconomyHandler.java#L157

Maybe this would make it possible to make PE compatible with Towny, since I don't like to change the economy plugin. PE is just too good for that :D

**Comment by lokka30** [comment]
Cheers, will look into it now :)

**Comment by lokka30** [comment]
@paulhlschr I've just pushed a commit for an upcoming release - check VaultImplementer class - would this tie better compatibility with Towny?

**Comment by paulhlschr** [comment]
I built a jar for myself to test it on my server. Unfortunately it is still not working (failing to deposit money into a town's bank returns the Towny message "You don't have that much.")

**Comment by paulhlschr** [comment]
I have just checked, what methods Towny uses and to be honest I can't find any missing method in your VaultImplementer class :o

**Comment by lokka30** [comment]
Hi, I will lock this issue and keep the discussion at https://github.com/TownyAdvanced/Towny/issues/3891 so everything's in one place.

**Comment by lokka30** [comment]
Should be fixed in the SpigotMC resource update: v1.9-RELEASE.
